product-name = "backend"
version = "0.1.0"
identifier = "com.backend.app"

[build]
before-dev-command = "cd ../frontend && pnpm dev"
dev-url = "http://localhost:3000"
before-build-command = "cd ../frontend && pnpm generate"
frontend-dist = "../frontend/dist"

[[app.windows]]
title = "backend"
width = 800
height = 600

[bundle]
active = false
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
